name: time_trial_bloc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  time_trial_api: ^1.0.0
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
