name: car_api
description: API to interact with the car
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  web_socket: ^0.1.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
