name: car_bloc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  overflow_car_api: ^1.0.0
  local_storage: ^1.0.0
  flutter_bloc: ^8.1.6
  flutter_vlc_player: ^7.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
