name: time_trial_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  async: ^2.11.0
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
