name: app_utilities
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  
  car_api: ^1.0.0
  car_bloc: ^1.0.0
  file_picker: ^8.1.6
  flutter_bloc: ^8.1.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
